In [2]:
## Numpy----# creat list 

In [4]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [5]:
import numpy as np

In [6]:
np.__version__

'1.26.4'

In [3]:
my_list = [10,20,30,40,50]
my_list

[10, 20, 30, 40, 50]

In [4]:
type(my_list)

list

In [9]:
arr = np.array(my_list) 
arr

array([10, 20, 30, 40, 50])

In [10]:
print(type(arr))
print(type(my_list))

<class 'numpy.ndarray'>
<class 'list'>


In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(30,40)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [13]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [14]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [15]:
np.arange(10,30,30, 3)

TypeError: Cannot interpret '3' as a data type

In [16]:
np.arange(8,20)

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.arange(20,8)

array([], dtype=int32)

In [18]:
np.arange(-20,8)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [19]:
n = np.arange(-20,8)
n

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [20]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros(3, dtype=int)

array([0, 0, 0])

In [22]:
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [24]:
np.zeros((3,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [25]:
nd = np.zeros((5,9), dtype = int)
nd

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [26]:
np.ones(3)

array([1., 1., 1.])

In [27]:
np.ones(3)

array([1., 1., 1.])

In [28]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [29]:
nd1 = np.ones((10,10), dtype = int)
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [30]:
nd

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [7]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [8]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [9]:
print(np.zeros(n,dtype=int))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [10]:
n

(6, 7)

In [12]:
n1

(6, 8)

In [13]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [18]:
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [19]:
np.ones(2)

array([1., 1.])

In [20]:
np.ones((2,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.ones((6,10),dtype = int) 

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [22]:
range(5)

range(0, 5)

In [23]:
r = range(5)
r

range(0, 5)

In [24]:
for i in r:
    print(i)

0
1
2
3
4


In [25]:
list(range(5))

[0, 1, 2, 3, 4]

In [26]:
range(1,10)

range(1, 10)

In [27]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [28]:
list(range(1,10,3))

[1, 4, 7]

In [29]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [30]:
np.random.rand(5)

array([0.59831393, 0.98476651, 0.90202071, 0.76025866, 0.66126479])

In [31]:
np.random.rand(2,4)

array([[0.16898598, 0.28810359, 0.49557793, 0.9298489 ],
       [0.76179024, 0.27409152, 0.97264404, 0.17660612]])

In [32]:
np.random.randint(2,4)

3

In [33]:
np.random.randint(2,20)

9

In [34]:
np.random.randint(0,1) 

0

In [35]:
np.random.randint(10,20,5)

array([13, 15, 15, 12, 10])

In [36]:
np.random.randint(1,6,4)

array([3, 4, 4, 4])

In [37]:
np.random.rand(3)

array([0.481875  , 0.49931665, 0.63941202])

In [38]:
np.random.randint(1)

0

In [39]:
np.random.randint(-30,20,10) 

array([  4,  -2,  -2,  17, -17,  -8,  10,  -3,  -1,  15])

In [40]:
np.random.randint(20,30,10)

array([23, 28, 29, 26, 28, 24, 29, 27, 21, 26])

In [41]:
np.random.randint(5,9)

6

In [42]:
np.random.randint(10,21,3)

array([13, 12, 11])

In [43]:
np.random.randint(1,12,10)

array([ 7,  8,  6,  3,  6,  1,  8, 10, 10,  7])

In [44]:
np.random.randint(10,40,(10,10))

array([[23, 12, 19, 21, 28, 24, 13, 28, 23, 37],
       [24, 17, 38, 20, 19, 36, 24, 35, 33, 24],
       [28, 31, 37, 25, 10, 17, 33, 21, 35, 18],
       [28, 30, 30, 16, 37, 33, 15, 30, 31, 21],
       [26, 25, 31, 26, 16, 37, 16, 12, 39, 38],
       [36, 27, 29, 38, 37, 25, 15, 28, 23, 14],
       [27, 14, 16, 13, 38, 26, 12, 32, 15, 15],
       [23, 15, 15, 17, 23, 17, 15, 33, 12, 18],
       [25, 36, 10, 10, 33, 31, 37, 31, 10, 32],
       [21, 24, 34, 38, 36, 16, 25, 20, 36, 17]])

In [45]:
np.random.randint(1,100,(12,12))

array([[ 7, 56, 14, 55, 91,  3, 80, 95, 15, 30,  9, 86],
       [58, 38, 91, 88, 43,  6, 17, 78, 25, 37, 13, 34],
       [16, 56, 30, 30, 46, 78,  7, 66, 77, 33, 13, 77],
       [ 8, 49, 49, 28, 53, 56, 93, 99, 53, 53, 86, 32],
       [78, 20, 37, 74,  9, 52, 71, 99, 48, 16,  6,  5],
       [31, 98, 69, 99, 67, 40, 70,  5, 48, 52, 84, 30],
       [70,  4, 29, 37, 25, 78, 40, 37, 19, 33, 85, 34],
       [44, 26, 48,  7, 74, 68, 84, 54, 23, 37, 93, 15],
       [37, 81, 26, 32, 31, 40, 68,  4, 88, 98, 31, 48],
       [11,  2, 16, 73, 51, 49, 51, 73, 45, 80, 92, 87],
       [ 2, 12, 33, 76, 59, 25,  6, 18, 78, 65, 29, 29],
       [93, 69, 76, 36, 81, 68, 15, 24,  1,  1,  1, 59]])

In [46]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
np.arange(1,13).reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [48]:
b = np.random.randint(10,20,(5,4))
b

array([[18, 17, 17, 17],
       [19, 11, 11, 14],
       [13, 14, 10, 14],
       [14, 19, 13, 11],
       [14, 18, 12, 16]])

In [49]:
type(b)

numpy.ndarray

In [50]:
b

array([[18, 17, 17, 17],
       [19, 11, 11, 14],
       [13, 14, 10, 14],
       [14, 19, 13, 11],
       [14, 18, 12, 16]])

In [51]:
b[:]

array([[18, 17, 17, 17],
       [19, 11, 11, 14],
       [13, 14, 10, 14],
       [14, 19, 13, 11],
       [14, 18, 12, 16]])

In [53]:
b[1:3]

array([[19, 11, 11, 14],
       [13, 14, 10, 14]])

In [54]:
b

array([[18, 17, 17, 17],
       [19, 11, 11, 14],
       [13, 14, 10, 14],
       [14, 19, 13, 11],
       [14, 18, 12, 16]])

In [55]:
b[1,2]

11

In [56]:
b[1,3]

14

In [57]:
b[1,-1]

14

In [58]:
b[2:3]

array([[13, 14, 10, 14]])

In [59]:
b[0:-2]

array([[18, 17, 17, 17],
       [19, 11, 11, 14],
       [13, 14, 10, 14]])

In [60]:
b[0,2]

17

In [61]:
b[-5,-3]

17

In [62]:
b

array([[18, 17, 17, 17],
       [19, 11, 11, 14],
       [13, 14, 10, 14],
       [14, 19, 13, 11],
       [14, 18, 12, 16]])

In [63]:
b[-4,2] 

11

In [64]:
np.random.randint(10,20,(4,4))

array([[10, 14, 17, 15],
       [16, 15, 15, 15],
       [19, 14, 18, 14],
       [18, 19, 14, 15]])

In [65]:
b[-4:2] 

array([[19, 11, 11, 14]])

In [66]:
## Operation

In [67]:
a = np.random.randint(10,20,10)
a

array([10, 12, 13, 10, 16, 13, 12, 12, 16, 11])

In [68]:
id(a)

1990255693616

In [70]:
arr2 = np.random.randint(0,100,(10,10))

In [71]:
arr2

array([[ 9, 81, 23,  9, 25, 71, 20, 61, 78,  5],
       [10, 60, 26, 34, 94, 47, 34, 73, 19, 81],
       [65, 25, 86, 11, 28, 43, 40, 95, 92, 35],
       [33, 46, 45,  4, 14,  4, 22, 98, 62, 50],
       [16, 62, 47, 39, 48, 27, 67,  4, 64, 87],
       [64, 54, 65, 87, 11, 54, 84, 24, 41, 65],
       [12, 14, 37, 83, 76, 69, 60, 42, 13, 16],
       [75, 41, 42, 54, 20, 70, 99,  1, 36, 12],
       [12, 66, 13, 37, 88, 78, 54, 77, 60, 49],
       [42, 86, 25, 76, 34, 20, 35, 67, 19, 56]])

In [75]:
arr=([0,1,2,3,4,5])

In [76]:
arr

[0, 1, 2, 3, 4, 5]

In [77]:
arr[:]

[0, 1, 2, 3, 4, 5]

In [78]:
arr[:4] 

[0, 1, 2, 3]

In [79]:
arr2[:]

array([[ 9, 81, 23,  9, 25, 71, 20, 61, 78,  5],
       [10, 60, 26, 34, 94, 47, 34, 73, 19, 81],
       [65, 25, 86, 11, 28, 43, 40, 95, 92, 35],
       [33, 46, 45,  4, 14,  4, 22, 98, 62, 50],
       [16, 62, 47, 39, 48, 27, 67,  4, 64, 87],
       [64, 54, 65, 87, 11, 54, 84, 24, 41, 65],
       [12, 14, 37, 83, 76, 69, 60, 42, 13, 16],
       [75, 41, 42, 54, 20, 70, 99,  1, 36, 12],
       [12, 66, 13, 37, 88, 78, 54, 77, 60, 49],
       [42, 86, 25, 76, 34, 20, 35, 67, 19, 56]])

In [80]:
arr2[0:5] 

array([[ 9, 81, 23,  9, 25, 71, 20, 61, 78,  5],
       [10, 60, 26, 34, 94, 47, 34, 73, 19, 81],
       [65, 25, 86, 11, 28, 43, 40, 95, 92, 35],
       [33, 46, 45,  4, 14,  4, 22, 98, 62, 50],
       [16, 62, 47, 39, 48, 27, 67,  4, 64, 87]])

In [81]:
arr2

array([[ 9, 81, 23,  9, 25, 71, 20, 61, 78,  5],
       [10, 60, 26, 34, 94, 47, 34, 73, 19, 81],
       [65, 25, 86, 11, 28, 43, 40, 95, 92, 35],
       [33, 46, 45,  4, 14,  4, 22, 98, 62, 50],
       [16, 62, 47, 39, 48, 27, 67,  4, 64, 87],
       [64, 54, 65, 87, 11, 54, 84, 24, 41, 65],
       [12, 14, 37, 83, 76, 69, 60, 42, 13, 16],
       [75, 41, 42, 54, 20, 70, 99,  1, 36, 12],
       [12, 66, 13, 37, 88, 78, 54, 77, 60, 49],
       [42, 86, 25, 76, 34, 20, 35, 67, 19, 56]])

In [82]:
arr2[1,4] 

94

In [83]:
arr2

array([[ 9, 81, 23,  9, 25, 71, 20, 61, 78,  5],
       [10, 60, 26, 34, 94, 47, 34, 73, 19, 81],
       [65, 25, 86, 11, 28, 43, 40, 95, 92, 35],
       [33, 46, 45,  4, 14,  4, 22, 98, 62, 50],
       [16, 62, 47, 39, 48, 27, 67,  4, 64, 87],
       [64, 54, 65, 87, 11, 54, 84, 24, 41, 65],
       [12, 14, 37, 83, 76, 69, 60, 42, 13, 16],
       [75, 41, 42, 54, 20, 70, 99,  1, 36, 12],
       [12, 66, 13, 37, 88, 78, 54, 77, 60, 49],
       [42, 86, 25, 76, 34, 20, 35, 67, 19, 56]])

In [84]:
arr2[-5,5]

54

In [85]:
arr2[-5,-5] 

54

In [86]:
arr2

array([[ 9, 81, 23,  9, 25, 71, 20, 61, 78,  5],
       [10, 60, 26, 34, 94, 47, 34, 73, 19, 81],
       [65, 25, 86, 11, 28, 43, 40, 95, 92, 35],
       [33, 46, 45,  4, 14,  4, 22, 98, 62, 50],
       [16, 62, 47, 39, 48, 27, 67,  4, 64, 87],
       [64, 54, 65, 87, 11, 54, 84, 24, 41, 65],
       [12, 14, 37, 83, 76, 69, 60, 42, 13, 16],
       [75, 41, 42, 54, 20, 70, 99,  1, 36, 12],
       [12, 66, 13, 37, 88, 78, 54, 77, 60, 49],
       [42, 86, 25, 76, 34, 20, 35, 67, 19, 56]])

In [87]:
arr2[-5,-5]

54

In [88]:
arr2

array([[ 9, 81, 23,  9, 25, 71, 20, 61, 78,  5],
       [10, 60, 26, 34, 94, 47, 34, 73, 19, 81],
       [65, 25, 86, 11, 28, 43, 40, 95, 92, 35],
       [33, 46, 45,  4, 14,  4, 22, 98, 62, 50],
       [16, 62, 47, 39, 48, 27, 67,  4, 64, 87],
       [64, 54, 65, 87, 11, 54, 84, 24, 41, 65],
       [12, 14, 37, 83, 76, 69, 60, 42, 13, 16],
       [75, 41, 42, 54, 20, 70, 99,  1, 36, 12],
       [12, 66, 13, 37, 88, 78, 54, 77, 60, 49],
       [42, 86, 25, 76, 34, 20, 35, 67, 19, 56]])

In [89]:
arr2[-1,-2]

19

In [90]:
arr2

array([[ 9, 81, 23,  9, 25, 71, 20, 61, 78,  5],
       [10, 60, 26, 34, 94, 47, 34, 73, 19, 81],
       [65, 25, 86, 11, 28, 43, 40, 95, 92, 35],
       [33, 46, 45,  4, 14,  4, 22, 98, 62, 50],
       [16, 62, 47, 39, 48, 27, 67,  4, 64, 87],
       [64, 54, 65, 87, 11, 54, 84, 24, 41, 65],
       [12, 14, 37, 83, 76, 69, 60, 42, 13, 16],
       [75, 41, 42, 54, 20, 70, 99,  1, 36, 12],
       [12, 66, 13, 37, 88, 78, 54, 77, 60, 49],
       [42, 86, 25, 76, 34, 20, 35, 67, 19, 56]])

In [91]:
arr2[::-1]

array([[42, 86, 25, 76, 34, 20, 35, 67, 19, 56],
       [12, 66, 13, 37, 88, 78, 54, 77, 60, 49],
       [75, 41, 42, 54, 20, 70, 99,  1, 36, 12],
       [12, 14, 37, 83, 76, 69, 60, 42, 13, 16],
       [64, 54, 65, 87, 11, 54, 84, 24, 41, 65],
       [16, 62, 47, 39, 48, 27, 67,  4, 64, 87],
       [33, 46, 45,  4, 14,  4, 22, 98, 62, 50],
       [65, 25, 86, 11, 28, 43, 40, 95, 92, 35],
       [10, 60, 26, 34, 94, 47, 34, 73, 19, 81],
       [ 9, 81, 23,  9, 25, 71, 20, 61, 78,  5]])

In [92]:
arr2[::-2] 

array([[42, 86, 25, 76, 34, 20, 35, 67, 19, 56],
       [75, 41, 42, 54, 20, 70, 99,  1, 36, 12],
       [64, 54, 65, 87, 11, 54, 84, 24, 41, 65],
       [33, 46, 45,  4, 14,  4, 22, 98, 62, 50],
       [10, 60, 26, 34, 94, 47, 34, 73, 19, 81]])

In [93]:
arr2[::-3]

array([[42, 86, 25, 76, 34, 20, 35, 67, 19, 56],
       [12, 14, 37, 83, 76, 69, 60, 42, 13, 16],
       [33, 46, 45,  4, 14,  4, 22, 98, 62, 50],
       [ 9, 81, 23,  9, 25, 71, 20, 61, 78,  5]])

In [94]:
arr2[:-3] 

array([[ 9, 81, 23,  9, 25, 71, 20, 61, 78,  5],
       [10, 60, 26, 34, 94, 47, 34, 73, 19, 81],
       [65, 25, 86, 11, 28, 43, 40, 95, 92, 35],
       [33, 46, 45,  4, 14,  4, 22, 98, 62, 50],
       [16, 62, 47, 39, 48, 27, 67,  4, 64, 87],
       [64, 54, 65, 87, 11, 54, 84, 24, 41, 65],
       [12, 14, 37, 83, 76, 69, 60, 42, 13, 16]])

In [95]:
arr

[0, 1, 2, 3, 4, 5]

In [104]:
arr = np.array([0,1,2,3,4,5])
arr

array([0, 1, 2, 3, 4, 5])

In [105]:
arr.max()

5

In [106]:
arr.mean()

2.5

In [107]:
arr.min()

0

In [108]:
arr.mean()

2.5

In [109]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [110]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

3.0

In [111]:
arr.reshape(3,2) 

array([[0, 1],
       [2, 3],
       [4, 5]])

In [112]:
arr.reshape(6,1) 

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [113]:
arr.reshape(1,6) 

array([[0, 1, 2, 3, 4, 5]])

In [114]:
arr

array([0, 1, 2, 3, 4, 5])

In [117]:
arr.reshape(2,3,order='C') 

array([[0, 1, 2],
       [3, 4, 5]])

In [118]:
arr.reshape(2,3,order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [119]:
arr.reshape(2,3,order='A')

array([[0, 1, 2],
       [3, 4, 5]])

In [120]:
arr

array([0, 1, 2, 3, 4, 5])

In [121]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [124]:
arr.reshape(1,6)  

array([[0, 1, 2, 3, 4, 5]])

In [125]:
arr.reshape(6,1) 

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [128]:
arr.reshape(3,2) 

array([[0, 1],
       [2, 3],
       [4, 5]])

In [129]:
## Indexing

In [130]:
mat = np.arange(0,100).reshape(10,10) 

In [131]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [157]:
row = 4
col = 5

In [148]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [158]:
mat[row,col]

45

In [159]:
col

5

In [160]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [161]:
mat[row,col] 

45

In [162]:
mat[4,5] 

45

In [163]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [164]:
col = 6

In [165]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [167]:
mat[6] 

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [168]:
# With Slices

In [169]:
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [170]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [171]:
mat[row,:] 

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [172]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [173]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [174]:
mat[:col] 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [175]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [176]:
row

4

In [177]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [178]:
mat[:row] 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [179]:
mat[row:] 

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [180]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [181]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [182]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [183]:
row

4

In [184]:
col

6

In [185]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [186]:
mat[1,4]

14

In [187]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [188]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [189]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [190]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [191]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [192]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [193]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [194]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [195]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [196]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [197]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [198]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [199]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [200]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [201]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [202]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [203]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [204]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [205]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [206]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [207]:
mat[1,6]

16

In [208]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [209]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [210]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [211]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [212]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [213]:
mat[3,5]

35

In [214]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [215]:
mat[1:2,2:4]

array([[12, 13]])

In [216]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [217]:
mat[2:3,2:3] 

array([[22]])

In [218]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [219]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [220]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [221]:
mat[2:3,4:5]

array([[24]])

In [222]:
## Masking

In [223]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [224]:
id(mat)

1990256292176

In [225]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [226]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [227]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [228]:
mat[mat==50]

array([50])

In [229]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [230]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [231]:
a1 = mat[mat<50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [232]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [233]:
a2 = mat[mat>50] 
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [234]:
a3 = mat[mat<=50] 
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [235]:
a4 = mat[mat==50]
a4

array([50])

In [236]:
## Program to generate OTP

In [241]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

otp_length = 4
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 5542


In [242]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

good even
good even
good even


In [243]:
def wish():
    print('good even')
wish()

wish()

wish()

good even
good even
good even


In [244]:
list1=['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x000001CF649DE900>


In [245]:
x = [1, 2, 3]
y = x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]
